### PR TITLE
adding example of sys executable app detection

### PR DESCRIPTION
**Pull request by nebukadhezer**

### CODE REVIEW

**Comment by nebukadhezer** [comment]
Hey here is a small example PR how this could work...
I tested this in maya with cprofile, the time from detect_app went down from
 0.026 seconds to  0.001 seconds.

cheers
johannes

**Comment by hannesdelbeke** [comment]
we can also check if we can import a module, instead of attempt to import it.
this should be faster too.

```python
import importlib

def check_module_import(module_name):
    try:
        importlib.util.find_spec(module_name)
        print("Module import successful.")
    except ImportError:
        print("Module import failed.")
```

I'm a bit hesitant to introduce 2 different logics for apps. one with interpreter path, and the other with modules.
the benefit of 0.02 sec on startup doesn't seem like it's worth complicating the code

**Comment by nebukadhezer** [comment]
That is true though the longer the list with supported apps will be the longer is the time for the last index that is being checked. 
I had written sth similiar in a company and hence cannot use it and we switched away from the import attempts. Also just an example you can be in nuke and have the shotgunapi available ... 
I quite liked the combination to use the executable where we can and fallback to imports where it won't work like in blender ...

But this is you project, I can easily maintain a fork. 

Cheers johannes

**Comment by hannesdelbeke** [comment]
> you can be in nuke and have the shotgunapi available

ah that's an issue, let me think this over 

> where it won't work like in blender

current blender versions will support this. only very old ones don't

**Comment by hannesdelbeke** [comment]
did some small refactor on top, please do check it out. (last 3 commits)

**Comment by nebukadhezer** [comment]
Hey, thanks for merging, I was on holiday, so I went silent...
I can make a PR for unimenu to reference detect-app.

The changes are good, makes it easier.
Again thanks for merging this.

**Comment by hannesdelbeke** [comment]
note to self. main purpose of this PR was to solve
> you can be in nuke and have the shotgunapi available

have run into this in Maya, when there was a module named unreal

**Pull request merged**
