### PR TITLE
needs to return app

### PR DESCRIPTION
**Pull request by nebukadhezer**
Hey sorry I had forgotten to PR this... 
either we return app or getattr(sys.modules[__name__], app.id)

### CODE REVIEW

**Comment by hannesdelbeke** [comment]
What s the change to app return for? 
Asking since some other repos depend on this i believe

**Comment by nebukadhezer** [comment]
For me this crashes with an error as app is an Instance of "class App"
 and not a str. Getattr needs a string so either we just return the app (as we already have it from the for loop)
or we use app.id to get another instance of the app we want to have.

Please just test this at your end, it does not work as it is atm.
For example in maya...

**Comment by hannesdelbeke** [comment]
ah thanks for explaining, will test

**Comment by nebukadhezer** [comment]
Any news here ?
Cheers

**Comment by hannesdelbeke** [comment]
havent been able to test
don't have free time atm. looking at the code it seems like it make sense though, merged!

**Comment by hannesdelbeke** [comment]
this PR possibly broke [plugget](https://github.com/plugget/plugget). bug: https://github.com/plugget/plugget-qt/issues/9
detect_app now thinks we run in Ansible (first app entry) instead of Blender

**Comment by hannesdelbeke** [comment]
confirmed  
- latest version 0.0.3 is working fine
- latest on this repo is broken

**Comment by hannesdelbeke** [comment]
was a small bug with upgrading the import fallback part, fixed now

**Pull request merged**
